import type { AttendanceRecord } from "../types/attendance";
import type { AttendanceSession } from "../types/attendance";
import type { AttendanceSummary } from "../types/attendance";

// ─── helpers ────────────────────────────────────────────────────────────────

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString("en-PH", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function formatTime(dateStr: string | null) {
  if (!dateStr) return "—";
  return new Date(dateStr).toLocaleTimeString("en-PH", {
    hour: "2-digit",
    minute: "2-digit",
  });
}

// ─── PDF via print ───────────────────────────────────────────────────────────

export function exportToPDF(
  session: AttendanceSession,
  records: AttendanceRecord[],
  className: string
) {
  const present = records.filter((r) => r.status === "present").length;
  const absent = records.filter((r) => r.status === "absent").length;

  const rows = records
    .map(
      (r, i) => `
      <tr class="${i % 2 === 0 ? "even" : ""}">
        <td>${i + 1}</td>
        <td class="mono">${r.student_number}</td>
        <td>${r.full_name}</td>
        <td><span class="badge ${r.status}">${r.status.charAt(0).toUpperCase() + r.status.slice(1)}</span></td>
        <td>${formatTime(r.scanned_at)}</td>
      </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Attendance – ${className}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 11px; color: #1a1a2e; padding: 32px; }
  .header { border-bottom: 2.5px solid #16a34a; padding-bottom: 14px; margin-bottom: 20px; }
  .header h1 { font-size: 20px; font-weight: 700; color: #14532d; letter-spacing: -0.3px; }
  .header .meta { margin-top: 4px; color: #6b7280; font-size: 11px; display: flex; gap: 20px; }
  .stats { display: flex; gap: 16px; margin-bottom: 18px; }
  .stat { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 10px 18px; text-align: center; }
  .stat .val { font-size: 22px; font-weight: 700; }
  .stat .lbl { font-size: 10px; color: #9ca3af; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 2px; }
  .stat.green .val { color: #16a34a; }
  .stat.red .val { color: #dc2626; }
  .stat.gray .val { color: #6b7280; }
  table { width: 100%; border-collapse: collapse; }
  thead tr { background: #f0fdf4; }
  th { text-align: left; padding: 9px 12px; font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: #166534; border-bottom: 1.5px solid #bbf7d0; }
  td { padding: 8px 12px; border-bottom: 1px solid #f3f4f6; vertical-align: middle; }
  tr.even td { background: #fafafa; }
  .mono { font-family: 'Courier New', monospace; font-size: 10px; color: #6b7280; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 20px; font-size: 10px; font-weight: 600; }
  .badge.present { background: #dcfce7; color: #166534; }
  .badge.absent { background: #fee2e2; color: #991b1b; }
  .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 10px; display: flex; justify-content: space-between; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
  <div class="header">
    <h1>${className} — Attendance Report</h1>
    <div class="meta">
      <span>📅 ${formatDate(session.attendance_date)}</span>
      <span>🖨 Printed ${new Date().toLocaleString("en-PH")}</span>
    </div>
  </div>
  <div class="stats">
    <div class="stat green"><div class="val">${present}</div><div class="lbl">Present</div></div>
    <div class="stat red"><div class="val">${absent}</div><div class="lbl">Absent</div></div>
    <div class="stat gray"><div class="val">${records.length}</div><div class="lbl">Total</div></div>
  </div>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Student No.</th>
        <th>Full Name</th>
        <th>Status</th>
        <th>Scanned At</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">
    <span>Generated by Students Attendance System</span>
    <span>Total: ${records.length} students</span>
  </div>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
}

// ─── Excel via SheetJS ───────────────────────────────────────────────────────

export async function exportToExcel(
  session: AttendanceSession,
  records: AttendanceRecord[],
  className: string
) {
  const XLSX = await import("xlsx");

  const present = records.filter((r) => r.status === "present").length;
  const absent = records.filter((r) => r.status === "absent").length;

  // Summary sheet
  const summaryData = [
    ["Attendance Report"],
    ["Class", className],
    ["Date", formatDate(session.attendance_date)],
    [""],
    ["Present", present],
    ["Absent", absent],
    ["Total", records.length],
  ];

  // Records sheet
  const recordsData = [
    ["#", "Student No.", "Full Name", "Status", "Scanned At"],
    ...records.map((r, i) => [
      i + 1,
      r.student_number,
      r.full_name,
      r.status.charAt(0).toUpperCase() + r.status.slice(1),
      formatTime(r.scanned_at),
    ]),
  ];

  const wb = XLSX.utils.book_new();

  // Summary sheet
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
  wsSummary["!cols"] = [{ wch: 18 }, { wch: 40 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

  // Records sheet
  const wsRecords = XLSX.utils.aoa_to_sheet(recordsData);
  wsRecords["!cols"] = [
    { wch: 4 },
    { wch: 16 },
    { wch: 36 },
    { wch: 12 },
    { wch: 14 },
  ];
  XLSX.utils.book_append_sheet(wb, wsRecords, "Records");

  const fileName = `attendance_${className.replace(/\s+/g, "_")}_${session.attendance_date}.xlsx`;
  XLSX.writeFile(wb, fileName);
}

// ─── Word via docx ───────────────────────────────────────────────────────────

export async function exportToWord(
  session: AttendanceSession,
  records: AttendanceRecord[],
  className: string
) {
  const {
    Document,
    Packer,
    Paragraph,
    Table,
    TableRow,
    TableCell,
    TextRun,
    HeadingLevel,
    AlignmentType,
    BorderStyle,
    WidthType,
    ShadingType,
  } = await import("docx");

  const present = records.filter((r) => r.status === "present").length;
  const absent = records.filter((r) => r.status === "absent").length;

  const headerCellStyle = (text: string) =>
    new TableCell({
      shading: { type: ShadingType.SOLID, color: "166534", fill: "166534" },
      borders: {
        top: { style: BorderStyle.NONE },
        bottom: { style: BorderStyle.NONE },
        left: { style: BorderStyle.NONE },
        right: { style: BorderStyle.NONE },
      },
      children: [
        new Paragraph({
          children: [new TextRun({ text, bold: true, color: "FFFFFF", size: 20 })],
          alignment: AlignmentType.CENTER,
        }),
      ],
    });

  const dataCell = (text: string, highlight?: boolean) =>
    new TableCell({
      shading: highlight ? { type: ShadingType.SOLID, color: "F0FDF4", fill: "F0FDF4" } : undefined,
      borders: {
        top: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
        left: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
        right: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
      },
      children: [
        new Paragraph({
          children: [new TextRun({ text, size: 20 })],
          alignment: AlignmentType.CENTER,
        }),
      ],
    });

  const tableRows = [
    new TableRow({
      tableHeader: true,
      children: [
        headerCellStyle("#"),
        headerCellStyle("Student No."),
        headerCellStyle("Full Name"),
        headerCellStyle("Status"),
        headerCellStyle("Scanned At"),
      ],
    }),
    ...records.map(
      (r, i) =>
        new TableRow({
          children: [
            dataCell(String(i + 1), i % 2 === 0),
            dataCell(r.student_number, i % 2 === 0),
            dataCell(r.full_name, i % 2 === 0),
            dataCell(r.status.charAt(0).toUpperCase() + r.status.slice(1), i % 2 === 0),
            dataCell(formatTime(r.scanned_at), i % 2 === 0),
          ],
        })
    ),
  ];

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            text: `${className} — Attendance Report`,
            heading: HeadingLevel.HEADING_1,
            spacing: { after: 120 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Date: ", bold: true }),
              new TextRun(formatDate(session.attendance_date)),
            ],
            spacing: { after: 60 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Summary:  ", bold: true }),
              new TextRun({ text: `${present} Present`, color: "166534", bold: true }),
              new TextRun("   "),
              new TextRun({ text: `${absent} Absent`, color: "991B1B", bold: true }),
              new TextRun("   "),
              new TextRun(`${records.length} Total`),
            ],
            spacing: { after: 240 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: tableRows,
          }),
          new Paragraph({
            text: `Generated by Students Attendance System · ${new Date().toLocaleString("en-PH")}`,
            spacing: { before: 240 },
            run: { size: 18, color: "9CA3AF" },
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `attendance_${className.replace(/\s+/g, "_")}_${session.attendance_date}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Summary PDF via print ───────────────────────────────────────────────────

export function exportSummaryToPDF(
  rows: AttendanceSummary[],
  periodLabel: string,
  className: string
) {
  const tableRows = rows
    .map(
      (r, i) => `
      <tr class="${i % 2 === 0 ? "even" : ""}">
        <td>${r.period}</td>
        <td class="center">${r.total_sessions}</td>
        <td class="center present">${r.present_count}</td>
        <td class="center absent">${r.absent_count}</td>
      </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>${periodLabel} Summary – ${className}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 11px; color: #1a1a2e; padding: 32px; }
  .header { border-bottom: 2.5px solid #16a34a; padding-bottom: 14px; margin-bottom: 20px; }
  .header h1 { font-size: 20px; font-weight: 700; color: #14532d; }
  .header .meta { margin-top: 4px; color: #6b7280; font-size: 11px; }
  table { width: 100%; border-collapse: collapse; }
  thead tr { background: #f0fdf4; }
  th { text-align: left; padding: 9px 12px; font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: #166534; border-bottom: 1.5px solid #bbf7d0; }
  th.center { text-align: center; }
  td { padding: 8px 12px; border-bottom: 1px solid #f3f4f6; }
  td.center { text-align: center; }
  tr.even td { background: #fafafa; }
  td.present { color: #16a34a; font-weight: 600; }
  td.absent { color: #dc2626; font-weight: 600; }
  .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 10px; display: flex; justify-content: space-between; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
  <div class="header">
    <h1>${className} — ${periodLabel} Attendance Summary</h1>
    <div class="meta">🖨 Printed ${new Date().toLocaleString("en-PH")}</div>
  </div>
  <table>
    <thead>
      <tr>
        <th>${periodLabel}</th>
        <th class="center">Sessions</th>
        <th class="center">Present</th>
        <th class="center">Absent</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <div class="footer">
    <span>Generated by Students Attendance System</span>
    <span>${rows.length} ${periodLabel.toLowerCase()}${rows.length !== 1 ? "s" : ""}</span>
  </div>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
}

// ─── Summary Excel ───────────────────────────────────────────────────────────

export async function exportSummaryToExcel(
  rows: AttendanceSummary[],
  periodLabel: string,
  className: string
) {
  const XLSX = await import("xlsx");

  const data = [
    [`${periodLabel} Attendance Summary — ${className}`],
    [`Printed: ${new Date().toLocaleString("en-PH")}`],
    [],
    [periodLabel, "Sessions", "Present", "Absent"],
    ...rows.map((r) => [r.period, r.total_sessions, r.present_count, r.absent_count]),
  ];

  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.aoa_to_sheet(data);
  ws["!cols"] = [{ wch: 20 }, { wch: 12 }, { wch: 12 }, { wch: 12 }];
  XLSX.utils.book_append_sheet(wb, ws, `${periodLabel} Summary`);

  const fileName = `${className.replace(/\s+/g, "_")}_${periodLabel.toLowerCase()}_summary.xlsx`;
  XLSX.writeFile(wb, fileName);
}

// ─── Summary Word ────────────────────────────────────────────────────────────

export async function exportSummaryToWord(
  rows: AttendanceSummary[],
  periodLabel: string,
  className: string
) {
  const {
    Document,
    Packer,
    Paragraph,
    Table,
    TableRow,
    TableCell,
    TextRun,
    HeadingLevel,
    AlignmentType,
    BorderStyle,
    WidthType,
    ShadingType,
  } = await import("docx");

  const headerCell = (text: string) =>
    new TableCell({
      shading: { type: ShadingType.SOLID, color: "166534", fill: "166534" },
      borders: {
        top: { style: BorderStyle.NONE },
        bottom: { style: BorderStyle.NONE },
        left: { style: BorderStyle.NONE },
        right: { style: BorderStyle.NONE },
      },
      children: [
        new Paragraph({
          children: [new TextRun({ text, bold: true, color: "FFFFFF", size: 20 })],
          alignment: AlignmentType.CENTER,
        }),
      ],
    });

  const dataCell = (text: string, highlight?: boolean) =>
    new TableCell({
      shading: highlight
        ? { type: ShadingType.SOLID, color: "F0FDF4", fill: "F0FDF4" }
        : undefined,
      borders: {
        top: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
        left: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
        right: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
      },
      children: [
        new Paragraph({
          children: [new TextRun({ text, size: 20 })],
          alignment: AlignmentType.CENTER,
        }),
      ],
    });

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            text: `${className} — ${periodLabel} Attendance Summary`,
            heading: HeadingLevel.HEADING_1,
            spacing: { after: 120 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Printed: ", bold: true }),
              new TextRun(new Date().toLocaleString("en-PH")),
            ],
            spacing: { after: 240 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                tableHeader: true,
                children: [
                  headerCell(periodLabel),
                  headerCell("Sessions"),
                  headerCell("Present"),
                  headerCell("Absent"),
                ],
              }),
              ...rows.map(
                (r, i) =>
                  new TableRow({
                    children: [
                      dataCell(r.period, i % 2 === 0),
                      dataCell(String(r.total_sessions), i % 2 === 0),
                      dataCell(String(r.present_count), i % 2 === 0),
                      dataCell(String(r.absent_count), i % 2 === 0),
                    ],
                  })
              ),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated by Students Attendance System · ${new Date().toLocaleString("en-PH")}`,
                size: 18,
                color: "9CA3AF",
              }),
            ],
            spacing: { before: 240 },
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${className.replace(/\s+/g, "_")}_${periodLabel.toLowerCase()}_summary.docx`;
  a.click();
  URL.revokeObjectURL(url);
}